from __future__ import annotations
from abc import ABC, abstractmethod
from src.domain.entities.value_objects import PatientId, DoctorId, AppointmentId, TimeSlot
from src.domain.entities.patient import Patient
from src.domain.entities.doctor import Doctor
from src.domain.entities.appointment import Appointment

class PatientRepository(ABC):
    @abstractmethod
    def next_id(self) -> PatientId: ...
    @abstractmethod
    def save(self, patient: Patient) -> None: ...
    @abstractmethod
    def find_by_id(self, pid: PatientId) -> Patient | None: ...
    @abstractmethod
    def find_by_email(self, email: str) -> Patient | None: ...

class DoctorRepository(ABC):
    @abstractmethod
    def next_id(self) -> DoctorId: ...
    @abstractmethod
    def save(self, doctor: Doctor) -> None: ...
    @abstractmethod
    def find_by_id(self, did: DoctorId) -> Doctor | None: ...

class AppointmentRepository(ABC):
    @abstractmethod
    def next_id(self) -> AppointmentId: ...
    @abstractmethod
    def save(self, appt: Appointment) -> None: ...
    @abstractmethod
    def find_by_id(self, aid: AppointmentId) -> Appointment | None: ...
    @abstractmethod
    def for_doctor_and_day(self, did: DoctorId, day: str) -> list[Appointment]: ...
    @abstractmethod
    def overlapping_for_doctor(self, did: DoctorId, slot: TimeSlot) -> list[Appointment]: ...